name: BountyfulWoodwork
version: '${version}'

main: com.nekyia.bountyfulWoodwork.BountyfulWoodwork
api-version: '26.3'
load: POSTWORLD
softdepend: [ Nexo ]

authors: [ gerryxn ]

commands:
  bw:
    description: Reloads the felling settings.
    usage: /bw reload
    aliases: [ woodwork ]
    permission: bountyfulwoodwork.admin

permissions:
  bountyfulwoodwork.admin:
    default: op
